import { NextResponse } from "next/server";
import { db } from "@/lib/db";
import type { Frequency, RecurringRule } from "@/generated/prisma/client";

// ---------------------------------------------------------------------------
// Helper: calculate the next generation date based on frequency
// ---------------------------------------------------------------------------
function calculateNextDate(current: Date, frequency: Frequency): Date {
  const next = new Date(current);

  switch (frequency) {
    case "DAILY":
      next.setUTCDate(next.getUTCDate() + 1);
      break;

    case "WEEKLY":
      next.setUTCDate(next.getUTCDate() + 7);
      break;

    case "BIWEEKLY":
      next.setUTCDate(next.getUTCDate() + 14);
      break;

    case "MONTHLY":
      addMonths(next, 1);
      break;

    case "BIMONTHLY":
      addMonths(next, 2);
      break;

    case "QUARTERLY":
      addMonths(next, 3);
      break;

    case "SEMIANNUAL":
      addMonths(next, 6);
      break;

    case "ANNUAL":
      addMonths(next, 12);
      break;

    default: {
      // Fallback: treat unknown frequency as monthly
      addMonths(next, 1);
    }
  }

  return next;
}

/**
 * Safely add N months to a Date, clamping to the last day of the target
 * month when the source day exceeds the target month length.
 *
 * Example: Jan 31 + 1 month -> Feb 28 (or 29 in leap years)
 */
function addMonths(date: Date, months: number): void {
  const originalDay = date.getUTCDate();
  date.setUTCMonth(date.getUTCMonth() + months);

  // If the day rolled over (e.g. 31 -> 3 of next month) clamp back
  if (date.getUTCDate() !== originalDay) {
    // Go to the last day of the previous month
    date.setUTCDate(0);
  }
}

// ---------------------------------------------------------------------------
// POST /api/cron/recurring-entries
// ---------------------------------------------------------------------------
export async function POST(request: Request) {
  // 1. Verify cron secret from Authorization header
  const authHeader = request.headers.get("authorization");
  if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const today = new Date();
  today.setUTCHours(0, 0, 0, 0);

  let processed = 0;
  let generated = 0;
  let deactivated = 0;
  const errors: string[] = [];

  try {
    // 2. Find all active RecurringRule where nextGenerationDate <= today
    const rules = await db.recurringRule.findMany({
      where: {
        active: true,
        nextGenerationDate: { lte: today },
      },
    });

    processed = rules.length;

    // 3. Process each rule inside its own transaction
    for (const rule of rules) {
      try {
        await db.$transaction(async (tx) => {
          // 3a. Create a StagingEntry with status AUTO_CLASSIFIED
          await tx.stagingEntry.create({
            data: {
              tenantId: rule.tenantId,
              source: "MANUAL", // generated by recurring rule automation
              status: "AUTO_CLASSIFIED",
              date: rule.nextGenerationDate,
              description: rule.name + (rule.description ? ` - ${rule.description}` : ""),
              amount: rule.amount,
              type: rule.type,
              chartOfAccountId: rule.chartOfAccountId,
              costCenterId: rule.costCenterId,
              supplierId: rule.supplierId,
              customerId: rule.customerId,
              bankAccountId: rule.bankAccountId,
              paymentMethodId: rule.paymentMethodId,
              notes: `Auto-generated from recurring rule: ${rule.name} (ID: ${rule.id})`,
              createdById: rule.createdById,
            },
          });

          generated++;

          // 3b. Calculate the next generation date based on frequency
          const nextDate = calculateNextDate(
            rule.nextGenerationDate,
            rule.frequency,
          );

          // 3c. Check whether the rule should be deactivated
          const shouldDeactivate =
            rule.endDate !== null && nextDate > rule.endDate;

          // 3d. Update the rule
          await tx.recurringRule.update({
            where: { id: rule.id },
            data: {
              nextGenerationDate: nextDate,
              ...(shouldDeactivate ? { active: false } : {}),
            },
          });

          if (shouldDeactivate) {
            deactivated++;
          }
        });
      } catch (err) {
        const message =
          err instanceof Error ? err.message : "Unknown error";
        errors.push(
          `Rule "${rule.name}" (${rule.id}): ${message}`,
        );
      }
    }

    return NextResponse.json({
      success: true,
      summary: {
        processed,
        generated,
        deactivated,
        errors,
      },
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";
    return NextResponse.json(
      { error: "Internal server error", details: message },
      { status: 500 },
    );
  }
}
